# Generated by Django 5.2.7 on 2025-10-30 09:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invited_users',
            field=models.ManyToManyField(blank=True, related_name='invited_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
