# Generated by Django 5.2.7 on 2025-10-30 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_invited_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rsvp',
            options={'ordering': ['-created_at']},
        ),
    ]
